name: End review
on:
  workflow_dispatch:
  pull_request:
    types: [closed]
    branches:
      - develop
jobs:  
  create-review-app:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          ref: ${{github.event.pull_request.head.ref}}
          fetch-depth: 0
      - run: |

          SOURCE_BRANCH_REF=$(git rev-parse --short HEAD)
          REVIEW_APP_NAME=heroku-pr-review-test-$SOURCE_BRANCH_REF

          echo "SOURCE_BRANCH_REF=$SOURCE_BRANCH_REF"
          echo "REVIEW_APP_NAME=$REVIEW_APP_NAME"

          curl -X DELETE https://api.heroku.com/apps/$REVIEW_APP_NAME \
              -H "Content-Type: application/json" \
              -H "Accept: application/vnd.heroku+json; version=3" \
              -H "Authorization: Bearer $HEROKU_API_KEY"

        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
