name: End review
on:
  workflow_dispatch:
  pull_request:
    types: [closed]
    branches:
      - develop
jobs:  
  create-review-app:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          ref: ${{github.event.pull_request.head.ref}}
          fetch-depth: 0
      - run: |
          chmod u+x ./cicd/destroy_review_app.sh
          ./cicd/destroy_review_app.sh
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
