name: Heroku review app with env var
on:
  workflow_dispatch:
jobs:  
  create-review-app-with-env-var:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          ref: ${{github.event.pull_request.head.ref}}
          fetch-depth: 0
      - name: Create review app
        run: |

          SOURCE_BRANCH_REF=$(git rev-parse --short HEAD)
          REVIEW_APP_NAME=$APP_NAME-$SOURCE_BRANCH_REF

          echo "SOURCE_BRANCH_REF=$SOURCE_BRANCH_REF"
          echo "REVIEW_APP_NAME=$REVIEW_APP_NAME"

          curl -X POST https://api.heroku.com/apps \
              -H "Accept: application/vnd.heroku+json; version=3" \
              -H "Authorization: Bearer $HEROKU_API_KEY" \
              -H "Content-Type: application/json" \
              -d "{\"name\":\"$REVIEW_APP_NAME\", \"region\":\"eu\"}"

          git push \
              https://heroku:$HEROKU_API_KEY@git.heroku.com/$REVIEW_APP_NAME.git \
              $SOURCE_BRANCH_REF:refs/heads/main

          REVIEW_APP_URL="https://$REVIEW_APP_NAME.herokuapp.com/"


          ######################################################################
          # set Heroku secrets
          curl -X PATCH https://api.heroku.com/apps/$REVIEW_APP_NAME/config-vars \
              -H "Accept: application/vnd.heroku+json; version=3" \
              -H "Authorization: Bearer $HEROKU_API_KEY" \
              -H "Content-Type: application/json" \
              -d "{\"REACT_APP_API_URL\":\"$REACT_APP_API_URL\", \"MAPBOX_API_KEY\":\"MAPBOX_API_KEY\"}"
          ######################################################################

        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
          COMMENTS_URL: ${{ github.event.pull_request.comments_url }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          APP_NAME: heroku-pr-review-test
          REACT_APP_API_URL: ${{ secrets.REACT_APP_API_URL }}
          MAPBOX_API_KEY: ${{ secrets.MAPBOX_API_KEY }}
